export * from "@/infra/repositories/database/prisma/user"
export * from "@/infra/repositories/database/prisma/city"
export * from "@/infra/repositories/database/prisma/local"
export * from "@/infra/repositories/database/prisma/category"
export * from "@/infra/repositories/database/prisma/comment"
